#!/bin/bash
#> don't use #!/bin/csh -f --you lose the module comman
#SBATCH --partition=savio3
#SBATCH --account=co_aiolos
#SBATCH --qos=aiolos_savio3_normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=5
# Wall clock limit:
#SBATCH --time=1:00:00
# Mail me for any notification
#SBATCH --output=%N-%j.out
#SBATCH --mail-type=all
#SBATCH --mail-user=lynchlee90@gmail.com

#ulimit -s unlimited
#export KMP_STACKSIZE=9209715200


cd /global/home/users/chili/Collocation
source bin/activate

for year in $(seq -w 2001 2005); do
	{
		python Combinehv.py --start $year --end $year
	
	}&


done
wait
